# <span style="color:Thistle">Ejercicios NumPy - Sesión 2</span>
### <span style="color:beige">Python y NumPy - Tipos de Datos</span>
#### <span style="color:beige">Resuelve los siguientes ejercicios prácticos en Python con la librería NumPy:</span>



In [6]:
import numpy as np

1. Crea un array de NumPy a partir de la lista [1, 2, 3, 4, 5] y verifica su tipo de
dato usando el atributo dtype.

In [22]:
array = np.array([1,2,3,4,5])
print(array.dtype)

int64


2. Crea un array con np.array([3.14, 4, 2, 3]) y explica qué sucede
con los tipos de datos

In [ ]:
array = np.array([3.14,4,2,3])
print(array.dtype)
#Esto pasa por que si los tipo no coinciden, Numpy realiza una promocion

float64


3. Genera un array de 15 elementos relleno de ceros y fuerza que sea de tipo
int32.

In [23]:
array = np.zeros([15],dtype=np.int32)
print(array)
print(array.dtype)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
int32


4. Crea una matriz 4x6 rellena con el valor 7.5 usando np.full().

In [ ]:
np.full((4,6),7.5)

array([[7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5, 7.5]])

5. Usa np.arange() para crear un array con los números pares del 0 al 30
(sin incluir 30).

In [25]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

6. Genera un array de 8 valores equiespaciados (= a igual distancia entre dos
elementos) entre 0 y 10 usando np.linspace()

In [26]:
np.linspace(0,10,8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

7. Crea un array de 10 números aleatorios con distribución uniforme entre 0 y
1, y calcula su media usando .mean().

In [34]:
array = np.random.random(10)
print(array)
array.mean()


[0.02204884 0.67218781 0.41490608 0.84389771 0.61193078 0.22492786
 0.0981452  0.54528588 0.63575012 0.82055265]


np.float64(0.4889632914543999)

8. Genera una matriz 5x5 con valores aleatorios de distribución normal
(media=0, desviación=1) y usa np.random.seed(42) para hacer el
resultado reproducible.

In [37]:
np.random.seed(42)
np.random.normal(0,1,(5,5))

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337],
       [-0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783],
       [-0.56228753, -1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819, -0.54438272]])

9. Crea un array con 20 enteros aleatorios entre 5 y 15 (sin incluir 15) usando
np.random.randint().

In [40]:
np.random.randint(5,15,20)

array([ 9, 12, 14, 13, 13,  5, 13, 11, 13, 12,  5, 12, 12,  7,  5, 12,  7,
        7,  5,  9], dtype=int32)

10. Crea un array desde una lista Python [1, 2, 3] y luego crea un segundo
array del mismo tamaño pero con tipo float64. Compara ambos usando
dtype.

In [43]:
array = np.array([1,2,3])
array2 = np.array([1,2,3],dtype=np.float64)
print(array.dtype)
array2.dtype

int64


dtype('float64')