# Ejercicios NumPy - Sesión 4
## Python y NumPy - Agregaciones
### Resuelve los siguientes ejercicios prácticos en Python con la librería NumPy:

Dado el array notas usa la sintaxis de método (.min(), .max(), .sum()) para:
1. Encontrar la nota mínima y máxima.
2. Calcular la suma total de todas las notas.

In [2]:
import numpy as np

notas = np.array([6.5, 8.0, 4.3, 9.1, 7.7, 5.5, 10.0, 3.2])
print(notas.min())
print(notas.max())
print(notas.sum())

3.2
10.0
54.3


## Ejercicio 2 — Estadísticas descriptivas básicas
Con el mismo array notas del ejercicio anterior, calcula e imprime:
1. Media (mean)
2. Desviación estándar poblacional (std)
3. Mediana (np.median)

In [3]:
print(notas.mean())
print(notas.std())
print(np.median(notas))

6.7875
2.201384507531567
7.1


## Ejercicio 3 — Agregaciones sobre matriz 2D (axis)
1. ¿Cuál es la suma total de todos los elementos?
2. ¿Cuál es el mínimo de cada columna (axis=0)?
3. ¿Cuál es el máximo de cada fila (axis=1)?

In [4]:
M = np.array([[3, 7, 1, 9],
[4, 2, 8, 5],
[6, 0, 3, 4]])


print(M.sum())
print(M.min(axis=0))
print(M.max(axis=1))

52
[3 0 1 4]
[9 8 6]


## Ejercicio 4 — Índices del mínimo y máximo
Dado el array temperaturas que representa temperaturas diarias (lunes a domingo):
Consulta la tabla de funciones de agregación
1. Usa np.argmin() para saber en qué día (índice) hizo menos calor.
2. Usa np.argmax() para saber en qué día hizo más calor.

In [5]:
temperaturas = np.array([22, 18, 25, 30, 15, 28, 21])
dias = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]

dia_mascalor = np.argmax(temperaturas)
dia_menoscalor = np.argmin(temperaturas)

print(f"dia mas caluroso = {dias[dia_mascalor]}")
print(f"dia menos caluroso = {dias[dia_menoscalor]}")

dia mas caluroso = Jueves
dia menos caluroso = Viernes


## Ejercicio 5 — Trabajando con NaN
1. Calcula la media usando np.mean(). ¿Qué resultado obtienes?
2. Calcula la media usando np.nanmean(). ¿Cuál es la diferencia?
3. ¿Cuántos valores NaN hay en el array? (Pista: usa np.isnan() y np.sum().)

In [6]:
ventas = np.array([120.0, np.nan, 85.0, 200.0, np.nan, 150.0])
media = np.mean(ventas)
medianan = np.nanmean(ventas)
cant_NaN = np.sum(np.isnan(ventas))
print(f"Media = {media}")
print(f"Medianan = {medianan}")
print(f"Cantidad de NaNs en ventas = {cant_NaN}")

Media = nan
Medianan = 138.75
Cantidad de NaNs en ventas = 2


## Ejercicio 6 — np.any y np.all con condiciones
Crea un array de 20 números aleatorios enteros entre -10 y 10.
1. Usa np.any() para comprobar si existe algún valor negativo.
2. Usa np.all() para comprobar si todos los valores son menores que 15.
3. Usa np.sum() para contar cuántos valores son mayores que 0.

In [7]:
numeros = np.random.randint(-10,11,20)
cant_negativos = np.any(numeros)
menores = np.all(numeros)
mayores = np.sum(numeros)

## Ejercicio 7 — Agregaciones por filas y columnas: tabla de ventas
Crea una matriz de ventas donde las filas son productos (A, B, C) y las columnas
son meses (Enero, Febrero, Marzo, Abril):

1. Calcula el total vendido por cada producto (suma por filas).
2. Calcula la media de ventas por mes (media por columnas).
3. Encuentra el producto con mayor suma total usando np.argmax()

In [ ]:
ventas = np.array([
    [150, 200, 180, 220],
    [90, 110, 95, 130],
    [300, 280, 320, 310]])

meses = ["Enero","Febrero","Marzo","Abril"]

total_vendido = np.sum(ventas,axis=1)

media_mes = np.median(ventas,axis=0)

prod_mayor_suma_index = np.argmax(ventas)

print(total_vendido)
print(media_mes)
print(prod_mayor_suma_index)

[ 750  425 1210]
[150. 200. 180. 220.]
10


## Ejercicio 8 — Mini análisis exploratorio completo
Simula un dataset de 42 valores numéricos enteros representando las puntuaciones de
alumnos (entre 0 y 10) y calcula una tabla resumen completa:
- Número alumnos
- Media
- Desviación estándar
- Mínimo
- Mediana
- Máximo
- Rango

In [27]:
dataset = np.random.randint(0,11,42)

cant_alumnos = dataset.shape
media = np.mean(dataset)
desv_std = np.std(dataset)
minimo = np.min(dataset)
mediana = np.median(dataset)
maximo = np.max(dataset)
rango = maximo - minimo

print(f"dataset = {dataset}")
print(f"cantidad alumnos = {cant_alumnos}")
print(f"media = {media}")
print(f"desviacion estandar = {desv_std}")
print(f"valor minimo = {minimo}")
print(f"mediana = {mediana}")
print(f"valor maximo = {maximo}")
print(f"rango = {rango}")

dataset = [ 3  7  7  7  6  4  9  0  5  2  3  7  3  5  9  1  0  0  2  5  6  2 10  4
  3  8  2  2  4  7  8  3  2  8  5  1  8  8 10  1 10  5]
cantidad alumnos = (42,)
media = 4.809523809523809
desviacion estandar = 2.9779994502389657
valor minimo = 0
mediana = 5.0
valor maximo = 10
rango = 10
