# <span style="color:Thistle">Fundamentos de los arrays de NumPy</span>

#### <span style="color:beige">Sesión 3</span>

La manipulación de datos en Python es prácticamente sinónimo de manipulación de arrays NumPy: incluso <span style="color:Gold">herramientas como Pandas están construidas sobre el array de NumPy</span>.

Vamos a poner varios ejemplos de manipulación de arrays NumPy.


---
## Atributos de los arrays NumPy

Primero veamos algunos atributos útiles de los arrays. Empezaremos definiendo un array. 

Usaremos el generador de números aleatorios de NumPy, al que le fijaremos una `semilla` para garantizar que se generen los mismos arrays aleatorios cada vez que se ejecute este código:

In [1]:
import numpy as np
np.random.seed(0)  # semilla para reproducibilidad

x1 = np.random.randint(10, size=6)        # Array unidimensional

x1

array([5, 0, 3, 3, 7, 9], dtype=int32)

<div class="alert alert-block alert-info">
<b>Pregunta:</b> ¿Qué es una semilla?
</div>

<div class="alert alert-block alert-info">
<b>Pregunta:</b> ¿De qué tipo es el array? ¿Por qué?
</div>

Cada array tiene los atributos `ndim` (número de dimensiones), `shape` (tamaño de cada dimensión) y `size` (tamaño total del array):

In [2]:
print("número de dimensiones de x1: ", x1.ndim)
print("tamaño de cada dimensión de x1:", x1.shape)
print("tamaño total de x1: ", x1.size)
print("tipo del array", print(x1.dtype))

número de dimensiones de x1:  1
tamaño de cada dimensión de x1: (6,)
tamaño total de x1:  6
int32
tipo del array None


<div class="alert alert-block alert-success">
<b>Nota:</b> ndim y shape están más pensados para arrays de varias dimensiones. De momento nosotros no los vamos a usar, así que no nos aportan información útil.
</div>

Otro atributo útil es `dtype`, el tipo de dato del array:

In [3]:
print("dtype:", x1.dtype)

dtype: int32


Otros atributos son `itemsize`, que indica el tamaño (en bytes) de cada elemento del array, y `nbytes`, que indica el tamaño total (en bytes) del array:

In [4]:
print("itemsize:", x1.itemsize, "bytes")
print("nbytes:", x1.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 24 bytes


En general, `nbytes` es igual a `itemsize` multiplicado por `size`.

Resumiendo:

$nbytes = itemsize * size$

- `nbytes`: Tamaño total (en bytes)
- `itemsize`: Tamaño de cada elemento (en bytes)
- `size`: Número de elementos

<div class="alert alert-block alert-info">
<b>Pregunta:</b> ¿Te cuadra el tamaño de un entero (consulta la tabla de la sesión anterior)?
</div>

---
## Acceso a los Arrays por índice

Los índices en NumPy son como los de Python. 

En un array unidimensional, se puede acceder al valor _i_ (contando desde cero) especificando el índice deseado entre corchetes, <span style="color:Gold">vamos, como siempre</span>:

In [5]:
x1

array([5, 0, 3, 3, 7, 9], dtype=int32)

In [6]:
x1[0]

np.int32(5)

In [7]:
x1[4]

np.int32(7)

Para acceder desde el final del array, puedes usar índices negativos:

In [8]:
x1[-1]

np.int32(9)

In [9]:
x1[-2]

np.int32(7)

<div class="alert alert-block alert-info">
<b>Pregunta:</b> ¿Qué muestra x1[-4]?
</div>

Ten en cuenta que, a diferencia de las listas de Python, <span style="color:Gold">los arrays de NumPy tienen un tipo fijo</span>. Esto significa, por ejemplo, que si intentas insertar un valor de coma flotante en un array de enteros, el valor se truncará sin avisar.

In [10]:
x1[0] = 3.14159  # Pero el array es de ENTEROS así que lo trunca a 3!
x1

array([3, 0, 3, 3, 7, 9], dtype=int32)

---
## Subarrays: Slicing

Así como podemos usar corchetes para acceder a elementos individuales del array, también podemos usarlos para <span style="color:Gold">acceder a subarrays</span> con la notación conocida como *slice o slicing*, con los dos puntos (`:`).

La sintaxis de slicing de NumPy sigue la de la lista estándar de Python; para acceder a un slice del array `x`, usa:

```python
x[inicio:fin:paso]
```

Si alguno de estos no se especifica, toman los valores predeterminados `inicio=0`, `fin=tamaño de la dimensión`, `paso=1`.

### Subarrays

In [12]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<div class="alert alert-block alert-info">
<b>Pregunta:</b> ¿Qué hace arange?
</div>

In [13]:
x[:5]  # primeros cinco elementos

array([0, 1, 2, 3, 4])

In [14]:
x[5:]  # elementos desde el índice 5 hasta el final

array([5, 6, 7, 8, 9])

In [15]:
x[4:7]  # subarray central del 4 al 7

array([4, 5, 6])

In [16]:
x[::2]  # un elemento de cada dos

array([0, 2, 4, 6, 8])

In [17]:
x[1::2]  # un elemento de cada dos, empezando en el índice 1

array([1, 3, 5, 7, 9])

Un caso potencialmente confuso es cuando el valor de `paso` es negativo.

En general, cuando vemos un índice negativo nos parece un jaleo, pero una vez lo dominas, es muy práctico. Eso sí, hay que usarlos muchos para acostumbrarse. _En mi caso prácticamente los he aprendido de memoria porqué nunca me he llegado a acostumbrar._

En el caso de abajo, vamos a generar un array alrevés. Una vez lo entiendes, se convierte en una forma muy elegante de invertir un array, pero <span style="color:Gold">cuesta acostumbrarse</span>:

In [18]:
x[::-1]  # todos los elementos, invertidos

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

<div class="alert alert-block alert-info">
<b>Pregunta:</b> ¿Qué devuelve x[5::-2]?<br> El array es [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
</div>

### Subarrays como vistas sin copia

<div class="alert alert-block alert-danger">
<b>Cuidado:</b> Esta parte es fundamental, aseguraos de que os quede claro. 
</div>

Una cosa importante —y extremadamente útil— que hay que saber sobre los slices de arrays es que <span style="color:Gold">devuelven *vistas* en lugar de *copias*</span> de los datos del array. Esta es una de las áreas en las que el slicing de arrays NumPy difiere del slicing de listas de Python: en las listas, `los slices son copias`. Veamos nuestro array de antes:

In [13]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


Creemos otro pero alreves:

In [14]:
x_alreves = x[::-1]
print(x_alreves)

[9 8 7 6 5 4 3 2 1 0]


Ahora, si modificamos este array, ¡veremos que el array original también cambia! Observa:

In [15]:
x_alreves[0] = 1337
print(x)

[   0    1    2    3    4    5    6    7    8 1337]


Y por supuesto, el que has cambiado también:

In [16]:
print(x_alreves)

[1337    8    7    6    5    4    3    2    1    0]


<div class="alert alert-block alert-success">
<b>Nota:</b> Al principio, me costó creer que esto fuera así, era la primera vez que veía este tipo de dependencia en listas.
</div>

Pero, tiene su sentido.

Este comportamiento predeterminado es realmente útil: significa que <span style="color:Gold">cuando trabajamos con grandes conjuntos de datos</span>, podemos acceder y procesar partes de esos conjuntos sin necesidad de copiar el búfer de datos subyacente.

<div class="alert alert-block alert-info">
<b>Pregunta:</b> ¿Qué peligros implica este comportamiento?
</div>

### Creación de copias de arrays

A veces es útil copiar explícitamente los datos dentro de un array. Esto se puede hacer fácilmente con el método `copy()`:

In [23]:
x_copia = x.copy()
print(x_copia)

[   0    1    2    3    4    5    6    7    8 1337]


Si ahora modificamos este array, el array original no se ve afectado:

In [24]:
x_copia[9] = 999
print(x_copia)

[  0   1   2   3   4   5   6   7   8 999]


In [25]:
print(x)

[   0    1    2    3    4    5    6    7    8 1337]


---
## Concatenación y división de Arrays

Todas las funciones anteriores trabajaban con arrays individuales. También es posible combinar varios arrays en uno, y a la inversa, dividir un array en varios.

### Concatenación de arrays

La concatenación, o unión de dos arrays en NumPy, se realiza principalmente usando las funciones `np.concatenate`, `np.vstack` y `np.hstack`.

La más habitual es `np.concatenate`, que toma una tupla o lista de arrays como primer argumento:

In [27]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

También puedes concatenar más de dos arrays a la vez:

In [28]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


### División de arrays

La operación opuesta a la concatenación es la división, implementada por las funciones `np.split`, `np.hsplit` y `np.vsplit`. Para cada una de ellas, podemos pasar una lista de índices que indican los puntos de división:

In [31]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


<div class="alert alert-block alert-info">
<b>Pregunta:</b> ¿Qué significa 3 y 5 en la función split?
</div>

Fíjate que *2* puntos de división dan lugar a *3* subarrays. 