# Ejercicios de NumPy
### `np.where` · `np.all` · `np.any`

---

In [2]:
import numpy as np
print('NumPy version:', np.__version__)

NumPy version: 2.4.2


---
## Resumen de funciones

| Función | Descripción | Ejemplo |
|---|---|---|
| `np.where(cond, x, y)` | Devuelve `x` donde `cond` es True, `y` donde es False | `np.where(a > 0, a, 0)` |
| `np.all(cond)` | True si **todos** los elementos cumplen la condición | `np.all(a > 0)` |
| `np.all(cond, axis=0)` | Evalúa `all` por **columnas** | `np.all(M > 0, axis=0)` |
| `np.all(cond, axis=1)` | Evalúa `all` por **filas** | `np.all(M > 0, axis=1)` |
| `np.any(cond)` | True si **algún** elemento cumple la condición | `np.any(a < 0)` |
| `np.any(cond, axis=0)` | Evalúa `any` por **columnas** | `np.any(M < 0, axis=0)` |
| `np.any(cond, axis=1)` | Evalúa `any` por **filas** | `np.any(M < 0, axis=1)` |

---
## Ejercicio 1 — `np.where` básico
### Normalizar valores negativos

Dado el siguiente array de temperaturas diarias (en °C), reemplaza todas las temperaturas **negativas** por `0` (punto de congelación) y conserva el resto tal cual.

```
temperaturas = [-3, 12, -1, 25, 0, -8, 18, 7]
```

**Resultado esperado:** `[ 0 12  0 25  0  0 18  7]`

> *Pista: usa `np.where(condición, valor_si_True, valor_si_False)`*

In [ ]:
temperaturas = np.array([-3, 12, -1, 25, 0, -8, 18, 7])

temperaturas = np.where(temperaturas >= 0,temperaturas,0)

print(temperaturas)


array([ 0, 12,  0, 25,  0,  0, 18,  7])

---
## Ejercicio 2 — `np.where` con etiquetas
### Clasificar calificaciones

Tienes las calificaciones de 8 estudiantes. Crea un nuevo array de strings donde:
- Calificación **≥ 50** → `'aprobado'`
- Calificación **< 50** → `'suspendido'`

```
notas = [85, 42, 60, 73, 55, 91, 38, 67]
```

**Resultado esperado:**
`['aprobado' 'suspendido' 'aprobado' 'aprobado' 'aprobado' 'aprobado' 'suspendido' 'aprobado']`

> *Pista: `np.where` puede devolver strings como valores.*

In [13]:

notas = np.array([85, 42, 60, 73, 55, 91, 38, 67])

notas = np.where(notas >= 50,"aprobado","suspendido")

print(notas)



['aprobado' 'suspendido' 'aprobado' 'aprobado' 'aprobado' 'aprobado'
 'suspendido' 'aprobado']


---
## Ejercicio 3 — `np.where` en 2D
### Umbral en una matriz

Dada la siguiente matriz de pixeles en escala de grises (0–255), aplica un **umbral (threshold)** de 128:
- Valores **≥ 128** → `255` (blanco)
- Valores **< 128** → `0` (negro)

Esto simula una **binarización** de imagen.

```
pixeles = [[200,  50, 130],
           [ 80, 255,  10],
           [128,  64, 190]]
```

**Resultado esperado:**
```
[[255   0 255]
 [  0 255   0]
 [255   0 255]]
```

> *Pista: `np.where` funciona igual en arrays 2D.*

In [14]:

pixeles = np.array([[200,  50, 130],
                    [ 80, 255,  10],
                    [128,  64, 190]])

pixeles = np.where(pixeles >= 128,255,0)

print(pixeles)



[[255   0 255]
 [  0 255   0]
 [255   0 255]]


---
## Ejercicio 4 — `np.all` global
### Verificar que todos los valores son válidos

Tienes un array de porcentajes. Comprueba con una sola llamada a `np.all` si **todos** los valores están dentro del rango válido `[0, 100]`.

Prueba con los dos arrays siguientes y compara los resultados:

```
a = np.array([10, 55, 0, 100, 73])
b = np.array([10, 55, 0, 101, 73])  # 101 es inválido
```

**Resultados esperados:** `True` y `False`

> *Pista: sin `axis`, `np.all` reduce todo el array a un único booleano.*

In [21]:
a = np.array([10, 55, 0, 100, 73])
b = np.array([10, 55, 0, 101, 73])

res1 = np.all((a <= 100) & (a >= 0))
res2 = np.all((b <= 100) & (b >= 0))

print(res1)
print(res2)

True
False


---
## Ejercicio 5 — `np.all` con axis
### Validar datos por fila

Tienes una matriz donde cada **fila** representa los resultados de 3 sensores de una máquina. Un sensor está en buen estado si su valor es **> 0**.

Determina cuáles **máquinas** (filas) tienen **todos** sus sensores funcionando correctamente.

```
sensores = [[ 5,  3,  7],   # máquina 0
            [ 4, -1,  6],   # máquina 1  ← sensor defectuoso
            [ 2,  8,  1],   # máquina 2
            [-3,  5,  0],   # máquina 3  ← sensor defectuoso
            [ 9,  6,  4]]   # máquina 4
```

**Resultado esperado:** `[ True False  True False  True]`

> *Pista: usa `np.all(..., axis=1)` para evaluar cada fila.*

In [7]:

sensores = np.array([[ 5,  3,  7],
                     [ 4, -1,  6],
                     [ 2,  8,  1],
                     [-3,  5,  0],
                     [ 9,  6,  4]])



---
## Ejercicio 6 — `np.any` global
### Detectar si hay algún valor nulo

Tienes un array de mediciones. Usa `np.any` para comprobar si **existe algún** valor igual a `0` (dato faltante) en todo el array.

Prueba con los dos arrays siguientes:

```
x = np.array([3.2, 1.5, 4.8, 2.1])
y = np.array([3.2, 0.0, 4.8, 2.1])  # hay un cero
```

**Resultados esperados:** `False` y `True`

> *Pista: sin `axis`, `np.any` devuelve un único booleano para todo el array.*

In [22]:
x = np.array([3.2, 1.5, 4.8, 2.1])
y = np.array([3.2, 0.0, 4.8, 2.1])

res1 = np.any(x == 0)
res2 = np.any(y == 0)

print(res1)
print(res2)


False
True


---
## Ejercicio 7 — `np.any` con axis
### Detectar valores atípicos por columna

Tienes una matriz de ventas diarias por producto (columnas). Quieres saber si **algún día** las ventas de cada producto superaron las **100 unidades** (pico de demanda).

```
ventas = [[ 80, 120,  40],
          [ 60,  90,  30],
          [110,  85,  20],
          [ 70,  95,  50],
          [ 90, 105,  35]]
```

**Resultado esperado:** `[ True  True False]`  
(Productos 0 y 1 sí tuvieron pico; producto 2 nunca superó 100)

> *Pista: usa `np.any(..., axis=0)` para evaluar cada columna.*

In [ ]:

ventas = np.array([[ 80, 120,  40],
                   [ 60,  90,  30],
                   [110,  85,  20],
                   [ 70,  95,  50],
                   [ 90, 105,  35]])

np.any(ventas > 100,axis=0)

array([ True,  True, False])

---
## Ejercicio FINAL — Combinación
### Pipeline de limpieza de datos

Tienes un dataset de mediciones de temperatura con posibles **errores** (valores fuera del rango físico -50 °C a 60 °C) y **ceros** que representan datos faltantes.

Realiza las siguientes tareas en orden:

1. Usa **`np.any`** para detectar si existe algún valor fuera del rango válido en todo el array.
2. Usa **`np.all`** para verificar que todas las filas tienen al menos un valor no-cero.
3. Usa **`np.where`** para reemplazar los valores inválidos (< -50 o > 60) por `np.nan`.

```
datos = [[ 22.5,  18.0,  -5.3],
         [ 15.0,  99.0,  23.1],   # 99.0 es inválido
         [  0.0,  12.0,  -2.5],
         [-55.0,  30.0,  10.0],   # -55.0 es inválido
         [ 40.0,  38.0,  41.0]]
```

> *Pista: combina condiciones con `|` (OR) para detectar fuera de rango.
> Para `np.where` con `np.nan`, convierte el array a `float` primero.*

In [27]:

datos = np.array([[ 22.5,  18.0,  -5.3],
                  [ 15.0,  99.0,  23.1],
                  [  0.0,  12.0,  -2.5],
                  [-55.0,  30.0,  10.0],
                  [ 40.0,  38.0,  41.0]], dtype=float)

# 1. ¿Hay algún valor fuera de rango?
is_valido = np.any((datos > 60) | (datos < -50))
print(is_valido)

# 2. ¿Todas las filas tienen al menos un valor no-cero?
not_zero = np.all(datos != 0,axis=1)
print(not_zero)

# 3. Reemplazar inválidos por np.nan
datos = np.where((datos > 60) | (datos < -50),np.nan,datos)

print(datos)


True
[ True  True False  True  True]
[[22.5 18.  -5.3]
 [15.   nan 23.1]
 [ 0.  12.  -2.5]
 [ nan 30.  10. ]
 [40.  38.  41. ]]
